---
name: default
type: docker
kind: pipeline


steps:
  - name: test
    image: python
    commands:
      - pip install poetry
      - poetry install -v
      - poetry run pytest
      - poetry run mypy harpocrates

  - name: run
    image: python
    commands:
      - pip install .
      - python3 harpocrates/main.py --help
